-- =========================================================
-- BANCO DE DADOS DA AGENDA DO FOTÓGRAFO — NICOLAS MÁS
-- SUPABASE / POSTGRESQL
-- =========================================================

-- =========================================================
-- 1. TABELA DE CLIENTES
-- =========================================================

CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(150),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 2. TABELA DE AGENDAMENTOS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.calendario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    tiposessao VARCHAR(100) NOT NULL,
    local VARCHAR(150) NOT NULL,
    data_agendamento DATE NOT NULL,
    horario TIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pendente',
    observacao TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT calendario_cliente_fk
        FOREIGN KEY (cliente_id)
        REFERENCES public.clientes(id)
        ON DELETE SET NULL,

    CONSTRAINT calendario_status_check
        CHECK (
            status IN ('pendente', 'confirmado', 'cancelado', 'concluido')
        ),

    CONSTRAINT calendario_horario_unico
        UNIQUE (data_agendamento, horario)
);


-- =========================================================
-- 3. ÍNDICES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_calendario_data ON public.calendario(data_agendamento);
CREATE INDEX IF NOT EXISTS idx_calendario_status ON public.calendario(status);
CREATE INDEX IF NOT EXISTS idx_calendario_cliente ON public.calendario(cliente_id);


-- =========================================================
-- 4. RLS — CLIENTES E CALENDARIO
-- =========================================================

ALTER TABLE public.calendario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;


-- ---- SITE PÚBLICO ----
-- O visitante precisa conseguir criar um agendamento e um cliente,
-- mas NÃO pode ler/editar/apagar dados de ninguém.

DROP POLICY IF EXISTS "publico pode criar agendamento" ON public.calendario;
CREATE POLICY "publico pode criar agendamento"
ON public.calendario
FOR INSERT
TO anon
WITH CHECK (true);

DROP POLICY IF EXISTS "publico pode criar cliente" ON public.clientes;
CREATE POLICY "publico pode criar cliente"
ON public.clientes
FOR INSERT
TO anon
WITH CHECK (true);

-- O front-end também precisa LER a tabela calendario (sem dados
-- sensíveis) para saber quais horários já estão ocupados e não deixar
-- o visitante marcar em cima de outro agendamento.
DROP POLICY IF EXISTS "publico pode ver horarios ocupados" ON public.calendario;
CREATE POLICY "publico pode ver horarios ocupados"
ON public.calendario
FOR SELECT
TO anon
USING (true);


-- ---- ADMIN (usuário logado) ----

DROP POLICY IF EXISTS "admin pode visualizar agendamentos" ON public.calendario;
CREATE POLICY "admin pode visualizar agendamentos"
ON public.calendario FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "admin pode atualizar agendamentos" ON public.calendario;
CREATE POLICY "admin pode atualizar agendamentos"
ON public.calendario FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "admin pode excluir agendamentos" ON public.calendario;
CREATE POLICY "admin pode excluir agendamentos"
ON public.calendario FOR DELETE TO authenticated USING (true);

DROP POLICY IF EXISTS "admin pode visualizar clientes" ON public.clientes;
CREATE POLICY "admin pode visualizar clientes"
ON public.clientes FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "admin pode atualizar clientes" ON public.clientes;
CREATE POLICY "admin pode atualizar clientes"
ON public.clientes FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


-- =========================================================
-- 5. FUNÇÃO PARA ATUALIZAR updated_at
-- =========================================================

CREATE OR REPLACE FUNCTION public.atualizar_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS atualizar_clientes_updated_at ON public.clientes;
CREATE TRIGGER atualizar_clientes_updated_at
BEFORE UPDATE ON public.clientes
FOR EACH ROW EXECUTE FUNCTION public.atualizar_updated_at();

DROP TRIGGER IF EXISTS atualizar_calendario_updated_at ON public.calendario;
CREATE TRIGGER atualizar_calendario_updated_at
BEFORE UPDATE ON public.calendario
FOR EACH ROW EXECUTE FUNCTION public.atualizar_updated_at();


-- =========================================================
-- 6. VIEW PARA O PAINEL ADMIN
-- =========================================================

CREATE OR REPLACE VIEW public.agenda_completa AS
SELECT
    c.id, c.nome, c.telefone, c.tiposessao, c.local,
    c.data_agendamento, c.horario, c.status, c.observacao,
    c.created_at, c.cliente_id
FROM public.calendario c
ORDER BY c.data_agendamento ASC, c.horario ASC;
